app = "hakimi-bot-oa2khg"
primary_region = "cdg"

[env]
  PYTHONUNBUFFERED = "1"

kill_signal = "SIGINT"
kill_timeout = "5s"

[processes]
  app = "python main.py"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"

