app = "hakimi-bot-sunset-01"   # tout en minuscules, chiffres, tirets
primary_region = "cdg"

[env]
  PYTHONUNBUFFERED = "1"

auto_stop_machines = false
auto_start_machines = true
kill_signal = "SIGINT"
kill_timeout = "5s"

[processes]
  app = "python main.py"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"

