# fly.toml
app = "Hakimi_bot"           # <-- choisis un nom unique global
primary_region = "cdg"       # Paris

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

# Machines: ne pas s’arrêter automatiquement (sinon ton bot s’éteint)
auto_stop_machines = false
auto_start_machines = true
kill_signal = "SIGINT"
kill_timeout = "5s"

# Pas de service HTTP: on déclare juste le process à lancer
[processes]
  app = "python main.py"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"

